# Tasks to configure apache and start the service
- name: Install Apache service
  package:
    name: httpd
    state: present

- name: Copy web files
  copy:
    src: backend/
    dest: /var/www/html
    directory_mode: yes

- name: Start Apache service
  service:
    name: httpd
    state: started
